server:
  port: 8080  # API Gateway port

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE  # Load-balanced service name or direct URL (e.g., http://localhost:8081)
          predicates:
            - Path=/users/**

        - id: order-service
          uri: lb://DEMO-ORDER
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: lb://DEMO-PAYMENT
          predicates:
            - Path=/payments/**

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
